### ISSUE TITLE
Create a homepage 

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-frontend#100]
Title says it all!

**Comment by Ermish** [comment]
I’ll take this one

**Comment by ann-kilzer** [comment]
I am a bit confused on what this means, as we already have an extremely useable landing page. Adding more clicks between people and getting registered with a cancellation list could degrade user experience.

Might be good to coordinate with Teresa on one like this? She can help guide us on UI/UX. Or perhaps make a quick mockup on paper, Figma, to show us what you have in mind?

**Comment by Ermish** [comment]
- why: since we’ll be having more than one product, it would make sense to have a central home page as the cancellations shouldn’t be the landing page for the other products. 
- the cancellations page would still be kept simple IX and agree with the validity of simple UX. This would be SEO compliant and  be the primary page from google / shared links. 
- for the design, sounds great! I’ll see what I can wireframe up and would love to sync with @ourjapanlife/designers-creatives. Personally, got some UX experience myself

**Comment by mdboop** [comment]
I'm in agreement with @Ermish that a homepage has a lot of merit, but I very strongly agree with @ann-kilzer's point that we should not create any friction. If you think about what this site is at it's core, it's actually very closely aligned with something like Airbnb, Tablelog, etc. anything related to reservations. You land, and immediately want to seek information about making a vaccine appointment somewhere in your region (if available). @theyokohamalife had some great points that people will travel far and wide to secure an appointment, but to me, this site calls for a search bar that is top and center of the main page.

You can add and organize other information below that, but I think every step away from the current design needs to be weighed against Ann's point and LaShawn's goal to keep the info right there.

**Comment by Ermish** [comment]
Talking UX, a key thing to consider is that user's workflow does not have to interact with the homepage at all. 

### Example: 
- Google "vaccine cancellations"  or click link sent by friend
- sent directly to cancellations page 
-apply 
- (optional) click homepage to learn more about who we are and what we provide. 


_Side note_: this is how my last two companies literal workflow worked as well. Most people hit the search page not homepage first, then search page. People google "software engineer jobs in Tokyo" and it goes from google directly to the Indeed search results page. You can test it out 😀
