### ISSUE TITLE
Centralize DB methods

### ISSUE THREAD

**Issue by renderf0x** [ourjapanlife/findadoc-frontend#123]
Right now, calls to the DB are inlined in `<script />` tags directly, with references to specific tables and states in each individual component.

We should make a `DbManager` class of some sort, and share it across components.

Two ways I can see this going down:
1. Procedural - single class with methods like `persist_clinic`, `edit_clinic`, etc, which could be implemented as a mixin
2. ORM - We have generic `persist` etc methods, but also create specific classes for say, a user or clinic that represent them as data models and provide methods to edit from the db. The API to define a new clinic, for instance, then becomes something like - `let clinic = new Clinic(); /*... fill in info to object *.../; clinic.save()`

**AC**
- Collection names, and constants are centralized in one class
- Singular manager class exists
- Mechanism for sharing between components
- Existing components refactored to use this
- Tests

**Comment by renderf0x** [comment]
Ping for @Ermish , as we may just want to fold this into the API, and have our frontend use the API.

**Comment by Ermish** [comment]
I'm currently working on the API which will resolve most of the issues with our current client-side DB calls. 
For now, I don't think we'll need a `clinicService/Manager` yet, but when we have more complex logic it would make sense to migrate it. 

Personally, I want to make sure we separate data entities from the actions you can perform on them. There's a bunch of justifications for this that I'm happy to chat about on slack if anyone is interested. 

Also, if we start sharing more state, Vuex has a consistent pattern for solving some of these centralizing data management through `state`, getters`, `actions`, and `mutations` which reflects backend data management patterns.

**Comment by renderf0x** [comment]
Depending on the API, I could see a split  data object model + API actions pattern working pretty well.

Re: This issue and this weekend, what's your status on the API @Ermish ? should we do this DB method change in the interim?
