### ISSUE TITLE
Persist user's language choice

### ISSUE THREAD

**Issue by renderf0x** [ourjapanlife/findadoc-frontend#133]
*"As a user of the site, I would like to have the site appear in my chosen language every time I enter `findadoc.jp` into my browser url bar, so I can browse in a the language that is familiar to me and save toil to re-click the language settings"*

Right now, selecting a language from the left-hand menu redirects you to a `/language` url (for instance `findadoc.jp/es` for Spanish. However, if you re-enter `findadoc.jp` to go back to the site, you'll return to English default unless another language is selected. We should save this setting direct the user to their previous choice of language.

**AC**
- On site load, the last used language setting is reused
- Changing this setting persists the new setting

**Out of scope**
- Complex user identification

**Comment by ann-kilzer** [comment]
Thanks for filing! Consider the [nuxt-i18n tooling](https://i18n.nuxtjs.org/browser-language-detection) which has some features for browser language detection.

There is also a built-in for `setLocaleCookie`: https://i18n.nuxtjs.org/api#setlocalecookie

**Comment by renderf0x** [comment]
I think that first is what we need for this one, then we should open a second issue upon closing this one for the browser language detection - a related but separate feature (and a good one).

**Comment by Al-un** [comment]
Currently having a look at this one. Regarding browser detection language, I might be tempted to ship it as well because it seems that the configurations are related / inter-dependent.
