### ISSUE TITLE
Footer UI Polishes

### ISSUE THREAD

**Issue by ann-kilzer** [ourjapanlife/findadoc-frontend#134]
Adjust footer based on discussion here: https://find-a-doc.slack.com/archives/C024WR4N66B/p1624458159009500

- [x] Better handling on iPhone 11
- [x] Color changes?
- [x] Ensure proper text contrast
- [x] Consider moving GitHub / Netlify to Sidebar

**Comment by mdboop** [comment]
I think we’d do well to change the layout as well. A designer can do more work later, but a simple approach would be to stop wrapping of the icon-text pairs and apply some alignment (center, etc.) for the main elements.

We just need to apply some flexbox rules that make sense, for example, something like this:

<img width="878" alt="image" src="https://user-images.githubusercontent.com/8826860/123119095-2fed9800-d47e-11eb-91e9-cf80c75fbce5.png">
