### ISSUE TITLE
migrate to vuetify sass styling. 

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-frontend#137]
vuetify's default styling brings in the entire css package (including fonts if I remember) . 
We should migrate to using the scss variables provided.
It's cleaner and should improve our performance.

AC

- [ ] Disable vuetify's default css library integration
- [ ] Migrate existing components to use vuetify provided sass variables.  (This may need to be broken down into sub-issues.)
    - We basically want to build our own design system starting with variables that set vuetify's optional sass variables. For example, [this vuetify button styling](https://vuetifyjs.com/en/api/v-btn/#sass-btn-icon-padding) can be changed by sass variables. 
    - [ ] Create a root level `_variables.scss` for our global style variables. 
    - [ ] Create a vuetify specific `_vuetifyVariables.scss` for specifically styling vuetify components at the global level. This can reuse variables from our `_variables.scss` file. like `$vuetify-button-size: $ourbuttonsize`.
    - Why create two? To maintain a consistent design experience within vuetify components, custom components, and any new systems. 
    - [ ] Figure out how to easily include vuetify sass variables writting within the component. We don't want everything in the global for all component styling, just global defaults. 
- [ ] Test all the things.

**Comment by ann-kilzer** [comment]
Related #61

**Comment by theyokohamalife** [comment]
Related #189

**Comment by ermish** [comment]
updated description with a little more explanation on how vuetify sass styling works and provided an example of their sass variables API.
