### ISSUE TITLE
Responsive Layout for testimonials / About page

### ISSUE THREAD

**Issue by ann-kilzer** [ourjapanlife/findadoc-frontend#148]
Follow up from previous comments: https://github.com/ourjapanlife/findadoc-frontend/pull/79#pullrequestreview-687824304

and https://github.com/ourjapanlife/findadoc-frontend/pull/79#issuecomment-864427326

Check with Teresa on this as she is working on the About Page layout

**Comment by renderf0x** [comment]
Current mock is here:
https://www.figma.com/proto/kdgcV9gd3cOeiSgoXY6VLM/Find-a-Doc?node-id=42%3A826&scaling=min-zoom&page-id=0%3A1&hotspot-hints=0&hide-ui=1

(There are some changes to the twitter widget on [this mock](https://www.figma.com/proto/kdgcV9gd3cOeiSgoXY6VLM/Find-a-Doc?node-id=94%3A1172&scaling=min-zoom&page-id=94%3A477&hide-ui=1) that will be included in the update to #193 )

Thanks to @thehamspecial
