### ISSUE TITLE
Selected language visibility in navigation drawer

### ISSUE THREAD

**Issue by theyokohamalife** [ourjapanlife/findadoc-frontend#150]
The selected language is too dark to be visible in the navigation drawer.

![Screen Shot 2021-06-24 at 10 04 51 PM (2)](https://user-images.githubusercontent.com/31802656/123267749-507a2880-d538-11eb-9a87-c098fce1e84e.png)

**Comment by ann-kilzer** [comment]
Ahh I just noticed this in #151.

It's not just in the languages, it's on the other parts of the toolbar as well, including Home

<img width="348" alt="COVID-19_Vaccination_Info" src="https://user-images.githubusercontent.com/4602369/123290198-0ac75b00-d54c-11eb-9500-f59fd836a0bb.png">

**Comment by RossellaFer** [comment]
@theyokohamalife @ann-kilzer I made a PR for this - I could not run the linter on my terminal though so there might be some formatting issues
