### ISSUE TITLE
Create disclaimer / privacy policy page. 

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-frontend#163]
# Create disclaimer / privacy policy page

We need to protect ourselves and our users. 

### Acceptance Criteria

- [ ] Create new page
- [ ] Reference our License. 
- [ ] Link to this page from the rest of the app where needed. 
- [ ] Must include English and Japanese (in the case of a translation discrepancy, which version is valid? Can it be English)

**Comment by renderf0x** [comment]
> (in the case of a translation discrepancy, which version is valid? Can it be English)

Yes. At work we do this by adding in language saying that the Japanese versions are 'reference translations' and in case of disagreement the English versions take precedent.
