### ISSUE TITLE
Set up TEST environment

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-frontend#172]
After @theyokohamalife  and I had a meeting with Google, we decided to build a  Dev/QA environment for people to access while developing the site. 
This will simplify the setup process where no local db is required, but is still optional. 
It will also protect out production environment and reduce our risks from db access. 

### Dev Tasks

- [x] Create New Firebase Project
- [ ] Create Google Auth Group for moderators
- [ ] Create moderator accounts through firebase
- [ ] Add those accounts to the google groups
- [x] Create QA DB creation function (using backup data)
- [x] Add read-only Firebase QA key to .env file

**Comment by Ermish** [comment]
cc @theyokohamalife @ann-kilzer @renderf0x 

this is overlapping with the local environment work, so let's chat in slack if you want more details.

**Comment by renderf0x** [comment]
Hmm, ok, so this is recommended over the separate local DBs? Ok, gotcha. We can do one over the other so long as we have a non-prod account.
