### ISSUE TITLE
Migrate to em/rem instead of px

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-frontend#187]
It's a good practice to use `em`'s/`rem`s instead of `px` 

There's a lot of articles you can look at online around this. 
An easy highlight is the accessibility support for people that need larger fonts and properly scaling our site. 

### Acceptance criteria

- [ ] Convert each page to use em/rem instead of px.  
- [ ] For any exceptions, explain why `px` is needed
- [ ] Add a stylelint rule

For a visual example, here's a[ good example](https://type-scale.com/) of how cool `rem`'s are and how they provide a consistent experience when changing font size! (thanks @softwaredeveloptam)

**Comment by Al-un** [comment]
Based on [this article](https://webdesign.tutsplus.com/tutorials/comprehensive-guide-when-to-use-em-vs-rem--cms-23984), I would recommended to either go full `rem` or full `em` but not with a mix. Personal preference goes with `rem` as it is more predictable.

If `rem` is chosen, do we want to set up font-size in `<html>` or leave it to the browser?

- font-size set up: more predictable behaviour
- leave it to the browser (although most browser set font-size to 16px): better accessibility support. Usually considered as a best practice, but we have to ensure that if user change font-size is OS settings, it does not blow up our design.

(My bad, I am lazy to find the article about this point)

**Comment by Ermish** [comment]
> Based on [this article](https://webdesign.tutsplus.com/tutorials/comprehensive-guide-when-to-use-em-vs-rem--cms-23984), I would recommended to either go full `rem` or full `em` but not with a mix. Personal preference goes with `rem` as it is more predictable.
> 
> If `rem` is chosen, do we want to set up font-size in `<html>` or leave it to the browser?
> 
> * font-size set up: more predictable behaviour
> * leave it to the browser (although most browser set font-size to 16px): better accessibility support. Usually considered as a best practice, but we have to ensure that if user change font-size is OS settings, it does not blow up our design.
> 
> (My bad, I am lazy to find the article about this point)

Hey, sounds like you're familiar with this! Nice to hear. 
- I'm fine either way as long as it's consistent and also prefer `rem`
- My vote is to have font-size set up. It sets the "expected experience" but still allows them to change.

**Comment by Al-un** [comment]
@ermish , quick response to say that I agree with your choices considering the project.
I don't think our UI is complicated enough to bother about accessibility from a font size point of view.

As for my relationship with this topics, it just came up recently at work so it's all fresh in my head :)

**Comment by ermish** [comment]
added a cool example of rem's in description
