### ISSUE TITLE
[Feature Idea} Track the number of people who got a reservation via cancellation

### ISSUE THREAD

**Issue by OnigiriJack** [ourjapanlife/findadoc-frontend#188]
- Age range
- Vaccine type
- where and when
- Form for entering information
- Might be good to submit a receipt for verification. 

I just think this would be an interesting way to showcase the progress of the app. Please let me know if there is anyway that I can help. Awesome app!

**Comment by ann-kilzer** [comment]
Great feature idea, but we need to avoid handling PII to reduce risk.

**Comment by renderf0x** [comment]
We can easily avoid PII if we only allow for preset values and not freetext. 
Of course, if we ever want to go down the road of making a clinic review feature we'll need to solve that, but just for vaccines this should be doable.

**Comment by ermish** [comment]
@renderf0x true, we don't have to store any PII. We can just have to make sure there's no identifiable information stored. 
Since we're not tying it to a user, we could utilize recaptcha for bot/troll prevention

**Comment by renderf0x** [comment]
And thanks to @Ania-chan that recaptcha should be coming soon...
