### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by theyokohamalife** [ourjapanlife/findadoc-frontend#20]
- [x] The website field should validate that the input is a URL
- [ ] All fields should be alphanumeric (? see below for discussion)

**Comment by ann-kilzer** [comment]
Also, highly recommend [Vuelidate](https://vuelidate.js.org/), which includes URL validation and great documentation

**Comment by PsychicNoodles** [comment]
I'm working on this now; just to confirm, the error messages are not i18n-ified yet, right?

**Comment by ann-kilzer** [comment]
We had to revert this because we found a bug with submissions not going through. Hopefully we can fix on a branch and get this in again. Thanks everyone for your cooperation!

**Comment by PsychicNoodles** [comment]
Oh no! Do we know what the bug was?

**Comment by ann-kilzer** [comment]
I wasn't able to reproduce it myself, @theyokohamalife had reported it. If you recreate the PR, perhaps we can reproduce it and troubleshoot.
