### ISSUE TITLE
Add ReCAPTCHA to add clinic form

### ISSUE THREAD

**Issue by ann-kilzer** [ourjapanlife/findadoc-frontend#200]
To cut down on spam and junk submissions, add Google Recaptcha to add clinic form

- Prefer using V3 recaptcha for less user friction
- Do not fall back from V3 to V2 as this goes against recommended practices

Docs here: https://developers.google.com/recaptcha/

We will either need to use a backend, or leverage Netlify's recaptcha ability. Please coordinate with team admins (especially @ann-kilzer) so we can keep the production config under our Netlify or GCloud accounts

**Comment by Ermish** [comment]
I think firebase (which we're using) have some recaptcha support 
https://firebase.google.com/docs/app-check/web

**Comment by renderf0x** [comment]
That's a sweet guide - looks easy to get going with.

**Comment by Ania-chan** [comment]
If no one is working on this can I work on this feature? 🙏🏻

**Comment by ermish** [comment]
sounds good @Ania-chan ! 🙌
