### ISSUE TITLE
Japanese text breaks the layout [bug report]

### ISSUE THREAD

**Issue by spavikevik** [ourjapanlife/findadoc-frontend#206]
Apologies if it's been reported before but it seems that the Japanese text in the blue notices breaks the layout slightly (see screenshots) on iPhone 12 Pro.

![image](https://user-images.githubusercontent.com/4943250/123814485-af70e080-d930-11eb-9cc5-2ba0c5addf09.png)
![image](https://user-images.githubusercontent.com/4943250/123814504-b39cfe00-d930-11eb-9a45-e75191e59a8b.png)

**Comment by theyokohamalife** [comment]
Thank you for the report! Is this in Safari?

**Comment by ann-kilzer** [comment]
Suggested fix: Use Vuetify Breakpoints to move the button below the text on `xs` screens

**Comment by renderf0x** [comment]
I was able to reproduce this on the `iPhone 6/7/8 Plus` preset in Chrome dev console.

As a datapoint, and one way to fix, setting a `min-width` on the text column of 100px or so will also work.

**Comment by spavikevik** [comment]
I see this has been fixed already. Looks good!

(sorry for forgetting to say it's in Safari, but it seems it was there in Chrome as well per the other comments)

**Comment by renderf0x** [comment]
> I see this has been fixed already. Looks good!
> 
> (sorry for forgetting to say it's in Safari, but it seems it was there in Chrome as well per the other comments)

Oh yeah - Chrome we only used for the devtools / emulator alongside the XCode Simulator.

@theyokohamalife came up with a fix for the issue and got it in late last night.

Thanks for reporting!
