### ISSUE TITLE
Replace <v-html> with interpolated components

### ISSUE THREAD

**Issue by ann-kilzer** [ourjapanlife/findadoc-frontend#219]
`v-html` works, but leaves us at risk for XSS attacks. I propose we move away from this pattern in favor of [component interpolation](https://kazupon.github.io/vue-i18n/guide/interpolation.html)

- [ ] replace instances of v-html in the code
- [ ] update i18n keys to remove markup
- [ ] turn up the linter to forbid v-html

**Comment by renderf0x** [comment]
Rather than the `<i18n />` interpolation component, the [slots syntax usage](https://kazupon.github.io/vue-i18n/guide/interpolation.html#slots-syntax-usage) is arguably even better.
