### ISSUE TITLE
Make Alerts Closable 

### ISSUE THREAD

**Issue by theyokohamalife** [ourjapanlife/findadoc-frontend#23]
Users should be able to close the alerts that appear at the top of the page.

- [ ] Create a variable to store the state of the alert? Might not be needed with vuetify
- [x] Update the current alert to one that can be closed

![Screen Shot 2021-06-16 at 10 45 56 PM (2)](https://user-images.githubusercontent.com/31802656/122230563-ba6d4f00-cef4-11eb-9828-2a7cb798f88e.png)

**Comment by ann-kilzer** [comment]
Alerts are closable on main. If we want to tweak this, can always re-open.
