### ISSUE TITLE
Header Image Path

### ISSUE THREAD

**Issue by theyokohamalife** [ourjapanlife/findadoc-frontend#245]
The header image is stored as `/static/header-img.jpg` and should be accessible via `header-img.jpg`. It works at the root level locally and on prod. However, it doesn't work for the `/news/` subdirectory.

Ideally, we'd like to change the path for `<img src="http://findadoc.jp/header-img.jpg" />` in the `HeroSection.vue` component back to `header-img.jpg` and have it work for the news section as well.

<img width="575" alt="Screen Shot 2021-07-21 at 8 17 21 PM" src="https://user-images.githubusercontent.com/31802656/126480940-1eb4b5f9-ce84-4be1-bee9-6a1220e84f08.png">

**Comment by mimzivvimzi** [comment]
Hi! I'd like to work on this issue.
