### ISSUE TITLE
Tag Us String

### ISSUE THREAD

**Issue by theyokohamalife** [ourjapanlife/findadoc-frontend#257]
Suggestion from @bbqbum33: 

Add a localized string that says, `Tag us if you get a vaccination through the site` next to the `Donate` button on the About page.

**Comment by ann-kilzer** [comment]
Great idea, and we could leverage it to get more metrics on how many people have been vaccinated via our site. How should people be tagging us? E.g. a specific hashtag, or should we create a Twitter account for findadoc?
