### ISSUE TITLE
open sourcing & security concerns

### ISSUE THREAD

**Issue by mdboop** [ourjapanlife/findadoc-frontend#34]
@theyokohamalife, you mentioned on Twitter that you'd like to open-source this, but had some security concerns.

I need to take a deeper look at Nuxt and Firebase to see what's up, but as I suspected, the tokens in the nuxt config are already sent down to the client. Anyone who opens up devtools could grab the apiKey. I don't see anything else in the repo that would be a sensitive key, so if these config values are OK (which I'm assuming they're fine since this is boilerplate Nuxt config stuff), then we should be OK.

here's how it ends up in the minified code:

```
var Et = {
          apiKey: "<removed>",
          authDomain: "<removed>",
          databaseURL: "<removed>",
          projectId: "<removed>",
          storageBucket: "<removed>",
          messagingSenderId: "<removed>
          appId: "<removed>",
          measurementId: "<removed>",
        },
```

So, if you still want to open source this, that _should_ be possible, but we'd need to confirm the existing values exposed in the client are in fact not sensitive (I'm guessing it's fine but I haven't used Nuxt or Firebase before).

**Comment by ann-kilzer** [comment]
Related #68

**Comment by ann-kilzer** [comment]
Is this done?
