### ISSUE TITLE
Implement Pagination for the cancellation table

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-frontend#38]
The data set is small for now, but as it grows, this will become increasingly more valuable

- Made data calls smaller which means
  - saves money (less data transferred)
  - faster UI response time
  - less js rendering on client side.

**Comment by Al-un** [comment]
(Currently having a look at it). I am not familiar with Firebase API so I am exploring :stuck_out_tongue_closed_eyes: . Maybe related to #123 as it seems API calls need to be centralised. 

If someone wants to take this one, feel free.

**Comment by Al-un** [comment]
Leaving some notes here but I encountered some problems:

- *Clinic total count*:
  As suggested by [this StackOverflow](https://stackoverflow.com/questions/49979714/how-to-get-count-of-documents-in-a-collection) answer, the number of clinics has to be saved as a counter (see [Distributed counters](https://firebase.google.com/docs/firestore/solutions/counters))
- *Clinic search*:
  Search might not be real time, using Vuetify data table search, but must fire a new query. Potentially, it means that search has to become a form with a submit button but again, the total results count will not be returned by Firestore
- *`VDataTable` not updated*:
  At the moment, the pagination, with the little hack, properly loads the clinics 10 by 10 but the `<v-data-table>` does not get updated :sob: .

For the exploration I relied on docs:

- https://firebase.google.com/docs/firestore/query-data/get-data#get_all_documents_in_a_collection & https://firebase.google.com/docs/firestore/query-data/query-cursors
- https://vuetifyjs.com/en/components/data-tables/ & https://vuetifyjs.com/en/api/v-data-table/

FWIW, I tried the changes

```vue
<template>
    <v-data-table
      hide-default-footer
      :page.sync="currentPage"
    >...</v-data-table>

    <!-- WIP: Length is using a hacky value to allow next button to be always available -->
    <v-pagination
      v-model="currentPage"
      :length="currentPage + 1"
      @next="onNextClinicPage"
      @previous="onPrevClinicPage"
    ></v-pagination>
</template>

<script>
export default {
  data(){
    return {
      currentPage: 1
      // ...
    }
  },

  async mounted() {
    await this.loadClinics();
  },

  methods: {
    async loadClinics() {
      // Page is already loaded, do not reload it
      if (this.items.length < this.currentPage * this.itemsPerPage) {
        return;
      }

      this.loading = true;

      /** @type {import('firebase').default.firestore.Firestore} */
      const db = this.$fireModule.firestore();
      const query = db
        .collection("clinics")
        .orderBy("id")
        .startAt((this.currentPage - 1) * this.itemsPerPage)
        .limit(this.itemsPerPage);

      const results = await query.get();
      results.forEach((document) => {
        const clinic = document.data();
        clinic.id = document.id;

        this.items.push(clinic);
      });

      this.loading = false;
    },

    async onNextClinicPage() {
      await this.loadClinics();
    },

    onPrevClinicPage() {
      // do nothing, items already loaded
    },
  }
}
</script>
```
