### ISSUE TITLE
Create a kebab/dango menu on admin moderation table

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-frontend#51]
For our admin moderation table, we want to have a kebab/dango menu shown on each row.

should include: 
- delete option
- edit option

**Comment by ann-kilzer** [comment]
Can you please post a picture of what this type of menu looks like? When I google this, I see

<img width="649" alt="55df2bb5eaa98ce207337d00793b2ee8_jpg__650×501_" src="https://user-images.githubusercontent.com/4602369/123035606-8cbd6400-d426-11eb-9391-182e433fce0c.png">

**Comment by renderf0x** [comment]
Haha!
Try this ![image](https://user-images.githubusercontent.com/6155643/123048092-fcd4e580-d438-11eb-9285-973b12ca79bd.jpeg)

**Comment by ann-kilzer** [comment]
Ahh, so when you click it, it shows a drop-down? 

<img width="234" alt="Create_a_kebab_dango_menu_on_admin_moderation_table_·_Issue__51_·_ourjapanlife_findadoc-frontend" src="https://user-images.githubusercontent.com/4602369/123074503-5269bc00-d452-11eb-8098-2586ab5e6943.png">

**Comment by renderf0x** [comment]
Precisely. It's a way to indicate that there's an ingress to 'more options'.
