### ISSUE TITLE
Make the login page pretty ✨ 

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-frontend#58]
Login page could use

- a title
- some padding
- Could even use a fancy background is someone is feeling creative! (example: https://discord.com/login)

**Comment by renderf0x** [comment]
Dunno if this falls under 'pretty', but we should also note on the login page who can login (I think it's just admins now, right?)

**Comment by renderf0x** [comment]
A suggestion from Teresa: Use an image like this icon in the bottom of the menu:
https://fonts.google.com/icons?icon.query=admin

**Comment by ann-kilzer** [comment]
That icon is `shield-account-variant` in the material set. The solid version is `shield-account-variant`

**Comment by renderf0x** [comment]
Good deal @ann-kilzer . Let's definitely include using that icon and moving the menu item down and out of the way in this issue (or open one for that)

**Comment by renderf0x** [comment]
Moved the menu discussion out of this on and into #167

**Comment by 2moon** [comment]
I'd like to give it a try:
- add title
- tweak some spacing (padding/margin)
- design some fancy background and add it

**Comment by Ermish** [comment]
sounds good @2moon!
