### ISSUE TITLE
Suggested UI fixes for Table

### ISSUE THREAD

**Issue by ann-kilzer** [ourjapanlife/findadoc-frontend#63]
I have a few suggestions for the Table UI to better match Material UI styling

1. Use the same button styling between the "flag" and "note", e.g. remove the blue border and have them both be icons only. Ensure that the icons are the same size and both from the Material set.
2. "Click for more info" is a bit vague. Replace with the URL of the website (truncate to character limit and add '...' if too long)
3. Replace the word "Flag" with "Report" (This requires an i18n change which now must be handled via the other repo)

<img width="1250" alt="COVID-19_Vaccination_Info" src="https://user-images.githubusercontent.com/4602369/122540888-08549500-d064-11eb-9ae7-e2f826ca4dac.png">

**Comment by ann-kilzer** [comment]
That's a good idea!

**Comment by ann-kilzer** [comment]
Ahh, I see we could link the clinic name too. Will leave open but lower priority

**Comment by ann-kilzer** [comment]
Pardon my indecision. Going to close for now and bring it up as a design idea, but unsure if we should implement it yet.

**Comment by theyokohamalife** [comment]
> > "Click for more info" is a bit vague. Replace with the URL of the website (truncate to character limit and add '...' if too long)
> 
> For that matter, I wonder if it might be good to have the clinic name hyperlinked in the table here as well?
> There's probably a future iteration where clicking it brings you to a specific clinic page on findadoc, but for now it's not even a click target...

That's an excellent idea and would save us a column in the table!
