### ISSUE TITLE
Pagination not showing last page

### ISSUE THREAD

**Issue by theyokohamalife** [ourjapanlife/findadoc-frontend#93]
The pagination buttons don't allow the user to view the entries on the last page.

![Screen Shot 2021-06-21 at 11 01 48 PM (2)](https://user-images.githubusercontent.com/31802656/122775176-d6059a80-d2e4-11eb-9bd7-655139897284.png)

**Comment by amar-prabhu-29** [comment]
Hi,
Id like to start working on this and some other issue. Please let me know where i can get the API Key from.
