### ISSUE TITLE
Move nuxt to static mode and add loading zones

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-frontend#99]
This might improve client side perf, but we need to maintain a good user experience. To do this, we want to show "loading zones" (think when the page isn't loaded and there's an empty shell with a loading icon, until it's loaded)

### Acceptance Criteria

- [ ] Move nuxt to static mode
This will make the UI load dynamically. 
- [ ] add loading zones
Since the user may see sections loading async, we need nice loading visualizations before the table and content is rendered.  Aka “loading zones”

**Comment by ann-kilzer** [comment]
Check out the Progress components here: https://v15.vuetifyjs.com/en/components/progress

**Comment by Al-un** [comment]
(Question asked on Slack)
